### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by KjellConnelly** [butopen/redevtools#1]
Hi! Just trying this out for tailwind editing. Pasted code into console. Also tried to load it dynamically from astro project with a script tag and conditionally appending a script tag. Got these errors:

```javascript
DevTools failed to load source map: Could not parse content for https://r8s.io/index.js.map: Unexpected token '(', "(()=>{var "... is not valid JSON
```

```javascript
DevTools failed to load source map: Could not parse content for http://r8s.io/tailwind.js.map: Unexpected token 'v', "var cn=Obj"... is not valid JSON
```

Got this too, but not sure if it has anything to so with the problem:

```javascript
(index):62 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
```

Tried the following:
```javascript
// 1:
document.head.appendChild(document.createElement("script")).src = "//r8s.io"

// 2: 
import("//r8s.io")
re.tailwind()

// 3:
<script>
  if (window.location.href.indexOf("localhost") >= 0) {
    document.head.appendChild(document.createElement("script")).src = "https://r8s.io"
  }
</script>
```

Ideas?

**Comment by salvatoreromeo** [comment]
that are just warnings. You can safely ignore them.

to enable the tailwind inspector follows these steps:
1) open the chrome devtool console
2) paste `import("//r8s.io")` and press ENTER
3) click on the page and press ALT+t on your keyboard

Does it work?

**Comment by KjellConnelly** [comment]
Oh it actually does work. I didn't notice because the icon was so small and I didn't see any feedback when I pressed option+T. Thank you :)
